force-app/main/default/objects/PolymorphicJoin__c/PolymorphicJoin__c.object-meta.xml
<CustomObject>
    <label>Polymorphic Join</label>
    <nameField>
        <label>Polymorphic Join Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Polymorphic Joins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PolymorphicJoin__c/fields/LookupObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>LookupObjectAPIName__c</fullName>
    <label>Lookup Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PolymorphicJoin__c/fields/LookupRecordId__c.field-meta.xml
<CustomField>
    <fullName>LookupRecordId__c</fullName>
    <label>Lookup Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PolymorphicJoin__c/fields/NameField__c.field-meta.xml
<CustomField>
    <fullName>NameField__c</fullName>
    <label>Name Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PolymorphicJoin__c/fields/PolymorphicJoin__c.field-meta.xml
<CustomField>
    <fullName>PolymorphicJoin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PolymorphicJoin(For Testing)</label>
    <referenceTo>PolymorphicJoin__c</referenceTo>
    <relationshipLabel>Polymorphic Joins</relationshipLabel>
    <relationshipName>Polymorphic_Joins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PolySearchTest.cls
@isTest
private class PolySearchTest {
    static testMethod void validatePolySearch() {
        
        Account a = new Account();
        a.Name = 'Test Account';
        insert a;
        
        PolymorphicJoin__c pj = new PolymorphicJoin__c();
        pj.Name = 'Account';
        pj.LookupObjectAPIName__c = 'Account';
        pj.NameField__c = 'Name';
        pj.Type__c = 'Account';
        pj.LookupRecordId__c = a.Id;
        
        insert pj;
        
        PolymorphicJoin__c pj2 = new PolymorphicJoin__c();
        pj2.Name = 'Test Poly';
		pj2.PolymorphicJoin__c = pj.id;

        insert pj2;       
        
        List<List<SObject>> objectDataList = new List<List<SObject>>();
        objectDataList.add(new List<Account>{a});
        objectDataList.add(new List<PolymorphicJoin__c>{pj,pj2});
        
        Map<String,String> data = new Map<String,String>{
            'polyId' => pj2.PolymorphicJoin__c,
            'nameField' => 'Name',
            'objectAPIName' => 'Account',
            'lookupRecordId' => a.Id,
            'fieldAPIName' => 'PolymorphicJoin__c',
            'recId' => pj2.Id,
            'recObject' => 'PolymorphicJoin__c'
        };  
        
        PolySearch ps = new PolySearch();            
        PolySearch.checkCurrentValue('','','');
        PolySearch.checkCurrentValue('PolymorphicJoin__c',pj2.Id,'PolymorphicJoin__c');
        PolySearch.search('Test');
        PolySearch.getSearchResults(objectDataList);    
        PolySearch.updatePolyValue('{}');
        PolySearch.updatePolyValue(JSON.serialize(data));
    }
}